RET-2927
hmcts/et-sya-api pull request #319
Opened 2023-04-03 12:57 UTC by ikirsanov

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/RET-2927

### Change description ###
After sendNotification viewed it status should be updated to 'viewed'

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x ] No
```

2023-04-03 14:40 UTC, Itay-Kirsh commented on src/main/java/uk/gov/hmcts/reform/et/syaapi/controllers/ManageCaseController.java
> +        CaseDetails finalCaseDetails =  sendNotificationService.updateSendNotificationState(authorization, request);
remove extra space

2023-04-03 14:42 UTC, Itay-Kirsh approved these changes

2023-04-03 15:57 UTC, marcjudge approved these changes

2023-04-03 15:57 UTC, marcjudge commented on src/main/java/uk/gov/hmcts/reform/et/syaapi/controllers/ManageCaseController.java
> +    public ResponseEntity<CaseDetails> updateSendNotificationState(
I will approve but I think this should be a new controller. I'd also like to split out the TSE endpoints into a new controller in future.

2023-04-03 15:59 UTC, marcjudge requested changes

2023-04-04 08:21 UTC, ikirsanov commented on src/main/java/uk/gov/hmcts/reform/et/syaapi/service/SendNotificationService.java
> +    public CaseDetails updateSendNotificationState(String authorization, SendNotificationStateUpdateRequest request) {
Made changes

2023-04-04 09:42 UTC, marcjudge approved these changes

2023-04-04 09:48 UTC, Itay-Kirsh approved these changes

2023-04-04 12:37 UTC, merged