Test functional
hmcts/et-sya-api pull request #407
Opened 2023-07-12 16:29 UTC by robin-ieong

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x ] No
```

2023-07-18 09:27 UTC, marcjudge approved these changes

2023-07-19 13:12 UTC, furnivall requested changes
Sorry to do this, but could you add sad path tests for whatever you can?

2023-07-21 14:44 UTC, robin-ieong commented
> Sorry to do this, but could you add sad path tests for whatever you can?
Added response validations and sad paths, thanks.

2023-07-23 10:07 UTC, SunnyAyeni approved these changes

2023-07-23 11:39 UTC, hsjhita approved these changes

2023-07-23 11:40 UTC, merged