RET-3460-Final - Refactored GenericTypeItem to TypeItem
hmcts/et-sya-api pull request #669
Opened 2023-12-05 10:48 UTC by aaronjduffy

https://tools.hmcts.net/jira/browse/RET-3460

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2023-12-12 09:42 UTC, lvo700 submitted a review, later dismissed

2024-01-30 14:00 UTC, marcjudge commented on config/owasp/suppressions.xml
> +  <suppress>
Check if these suppressions are still needed

2024-01-30 15:13 UTC, lvo700 commented on build.gradle
> +  implementation group: 'com.github.hmcts', name: 'et-data-model', version:'RET-3460-Final-SNAPSHOT'
I think this needs to stay until it has been QA'd as they won't be able to verify it passes pipeline otherwise.

2024-01-30 15:15 UTC, lvo700 commented on config/owasp/suppressions.xml
> +  <suppress>
Looks like they are still needed. There doesn't seem to be a fix for the first one and the second two require azure migration in et-common.

2024-01-30 19:02 UTC, JackReevies requested changes

2024-01-30 19:02 UTC, JackReevies commented on src/main/java/uk/gov/hmcts/reform/et/syaapi/service/pdf/PdfService.java
> +        List<TypeItem<GenericTseApplicationType>> tseApplicationTypeItems,
`ListTypeItem<GenericTseApplication?` ?

2024-01-30 19:02 UTC, JackReevies commented on src/main/java/uk/gov/hmcts/reform/et/syaapi/service/utils/ClaimantTseUtil.java
> +        List<TypeItem<GenericTseApplicationType>> genericTseApplications) {
`ListTypeItem<GenericTseApplication?` ?

2024-01-31 15:07 UTC, lvo700 commented on config/owasp/suppressions.xml
> +  </suppress>
Bumped version

2024-01-31 15:09 UTC, lvo700 commented on src/main/java/uk/gov/hmcts/reform/et/syaapi/helper/TseApplicationHelper.java
> +        List<TypeItem<GenericTseApplicationType>> applications,
Refactored

2024-01-31 15:09 UTC, lvo700 commented on src/main/java/uk/gov/hmcts/reform/et/syaapi/helper/TseApplicationHelper.java
> +            responseToAdd.getSupportingMaterial().add(documentTypeItem);
Duplicates, removed

2024-01-31 15:10 UTC, lvo700 commented on src/main/java/uk/gov/hmcts/reform/et/syaapi/service/SendNotificationService.java
> +    private void setNonTribunalResponsesAsViewed(List<TypeItem<PseResponse>> responses) {
Refactored

2024-01-31 15:10 UTC, lvo700 commented on src/main/java/uk/gov/hmcts/reform/et/syaapi/service/pdf/PdfService.java
> +        List<TypeItem<GenericTseApplicationType>> tseApplicationTypeItems,
Refactored

2024-01-31 15:10 UTC, lvo700 commented on src/main/java/uk/gov/hmcts/reform/et/syaapi/service/utils/ClaimantTseUtil.java
> +        List<TypeItem<GenericTseApplicationType>> genericTseApplications) {
Refactored

2024-07-09 12:06 UTC, closed without merging