RET-5010: ECC WA Task
hmcts/et-sya-api pull request #854
Opened 2024-04-19 14:46 UTC by fergusoshea

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/RET-5010

### Change description ###
Update some WA enablers for ECC task

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2024-04-24 16:17 UTC, lvo700 approved these changes

2024-04-25 08:22 UTC, marcjudge approved these changes

2024-05-01 10:41 UTC, lvo700 submitted a review, later dismissed

2024-05-01 10:47 UTC, JackReevies requested changes

2024-05-01 10:47 UTC, JackReevies commented on src/main/java/uk/gov/hmcts/reform/et/syaapi/helper/NotificationsHelper.java
> +        if (isEccEnabled) {
Reverse this conditional please. ie `if (!isEccEnabled) { return; }`

2024-05-01 11:11 UTC, lvo700 approved these changes

2024-05-01 11:14 UTC, JackReevies approved these changes

2024-05-01 11:19 UTC, merged