RET 1026 - RESTful endpoint to return a stubbed response stream of a Hello World PDF
hmcts/et-sya-api pull request #92
Opened 2022-05-16 10:12 UTC by brendanmchugh

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/RET-1026

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2022-05-16 13:31 UTC, DarylBoam approved these changes
Tests working

2022-05-16 13:33 UTC, nickwest1 requested changes

2022-05-16 13:33 UTC, nickwest1 commented on src/main/java/uk/gov/hmcts/reform/et/syaapi/controllers/DocumentGenerationController.java
> +public class DocumentGenerationController {
Should have class level JavaDoc too

2022-05-16 13:33 UTC, nickwest1 commented on src/main/java/uk/gov/hmcts/reform/et/syaapi/controllers/DocumentGenerationController.java
> +    public ResponseEntity<byte[]> generatePdf(
public methods need JavaDoc

2022-05-16 13:33 UTC, nickwest1 commented on src/test/java/uk/gov/hmcts/reform/et/syaapi/controllers/DocumentGenerationControllerTest.java
> +    }
I wouldn't have thought this was necessary

2022-05-16 13:33 UTC, nickwest1 commented on src/test/java/uk/gov/hmcts/reform/et/syaapi/controllers/DocumentGenerationControllerTest.java
> +    );
To avoid obscure errors/exceptions when resource not found, better to initialise this variable in either a constructor, or in an @Setup method

2022-05-16 13:33 UTC, nickwest1 commented on src/test/java/uk/gov/hmcts/reform/et/syaapi/controllers/DocumentGenerationControllerTest.java
> +            Thread.currentThread().getContextClassLoader().getResourceAsStream("HelloWorld.pdf").readAllBytes();
See https://www.baeldung.com/reading-file-in-java
Shouldn't need Thread to read a resource from

2022-05-16 13:33 UTC, nickwest1 commented on src/main/java/uk/gov/hmcts/reform/et/syaapi/controllers/DocumentGenerationController.java
> +        return Thread.currentThread().getContextClassLoader().getResourceAsStream("HelloWorld.pdf").readAllBytes();
See https://www.baeldung.com/reading-file-in-java
Shouldn't need Thread to read a resource from

2022-05-16 13:33 UTC, nickwest1 commented on src/test/java/uk/gov/hmcts/reform/et/syaapi/controllers/DocumentGenerationControllerTest.java
> +    void shouldReturnPdfAsByteArray() {
test method names should conform to:
  when_then (but DPM complains about underscores, so change to whenThen)
So for this:
happyRequestReturnsExpectedByteArray

2022-05-20 11:00 UTC, nickwest1 approved these changes

2022-05-27 10:45 UTC, merged