Ret 1452 latest
hmcts/et-sya-api pull request #93
Opened 2022-05-16 14:14 UTC by vinothon84

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link (if applicable) ###

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2022-05-16 16:29 UTC, nickwest1 requested changes
Good job in general ;)

2022-05-16 16:29 UTC, nickwest1 commented on src/contractTest/java/uk/gov/hmcts/reform/et/syaapi/consumer/ccd/CcdGetCasesByCaseIdPactTest.java
> +        Map<String, String> responseHeaders = Map.of("Content-Type", "application/json");
Maybe a constant on the base class?

2022-05-16 16:29 UTC, nickwest1 commented on src/contractTest/java/uk/gov/hmcts/reform/et/syaapi/consumer/ccd/StartEventForCitizenConsumerTest.java
> +    protected Map<String, Object> addCaseTypeJurdisticaton() {
protected?

2022-05-16 16:29 UTC, nickwest1 commented on src/contractTest/java/uk/gov/hmcts/reform/et/syaapi/consumer/ccd/StartForCitizenConsumerTest.java
> +        public RequestResponsePact startForCitizen(PactDslWithProvider builder) {
public?

2022-05-16 16:29 UTC, nickwest1 commented on src/contractTest/java/uk/gov/hmcts/reform/et/syaapi/consumer/ccd/StartForCitizenConsumerTest.java
> +        Map<String, String> responseHeaders = Map.of("Content-Type", "application/json");
as constant?

2022-05-16 16:29 UTC, nickwest1 commented on src/contractTest/java/uk/gov/hmcts/reform/et/syaapi/consumer/ccd/StartEventForCitizenConsumerTest.java
> +    public static DslPart buildStartEventResponseWithEmptyCaseDetails(String eventId) {
Duplicate maybe?

2022-05-16 16:29 UTC, nickwest1 commented on src/contractTest/java/uk/gov/hmcts/reform/et/syaapi/consumer/ccd/StartForCitizenConsumerTest.java
> +    public static DslPart buildStartEventResponseWithEmptyCaseDetails(String eventId) {
Duplicate maybe?
As above

2022-05-16 16:29 UTC, nickwest1 commented on src/contractTest/java/uk/gov/hmcts/reform/et/syaapi/consumer/ccd/SubmitEventForCitizenConsumerTest.java
> +        public RequestResponsePact submitEventForCitizen(PactDslWithProvider builder) {
public?

2022-05-16 16:29 UTC, nickwest1 commented on src/contractTest/java/uk/gov/hmcts/reform/et/syaapi/consumer/ccd/SubmitEventForCitizenConsumerTest.java
> +        Map<String, String> responseHeaders = Map.of("Content-Type", "application/json");
As constant

2022-05-16 16:29 UTC, nickwest1 commented on src/contractTest/java/uk/gov/hmcts/reform/et/syaapi/consumer/ccd/SubmitEventForCitizenConsumerTest.java
> +        );
Javascript pattern, Keep bracket on same line as code.
Please review all of this PR for instances of this :)

2022-05-16 16:29 UTC, nickwest1 commented on src/contractTest/java/uk/gov/hmcts/reform/et/syaapi/consumer/ccd/SubmitEventForCitizenConsumerTest.java
> +    protected Map<String, Object> addCaseTypeJurdisticaton() {
proitected?

2022-05-16 16:29 UTC, nickwest1 commented on src/contractTest/java/uk/gov/hmcts/reform/et/syaapi/consumer/ccd/SubmitEventForCitizenConsumerTest.java
> +    public static DslPart buildCaseDetailsDsl(Long caseId) {
Duplicate?
As above

2022-05-16 16:29 UTC, nickwest1 commented on src/contractTest/java/uk/gov/hmcts/reform/et/syaapi/consumer/ccd/SubmitForCitizenConsumerTest.java
> +        public RequestResponsePact submitForCitizen(PactDslWithProvider builder) {
public?

2022-05-16 16:29 UTC, nickwest1 commented on src/contractTest/java/uk/gov/hmcts/reform/et/syaapi/consumer/ccd/SubmitForCitizenConsumerTest.java
> +        Map<String, String> responseHeaders = Map.of("Content-Type", "application/json");
As above, constant

2022-05-16 16:29 UTC, nickwest1 commented on src/contractTest/java/uk/gov/hmcts/reform/et/syaapi/consumer/ccd/SubmitForCitizenConsumerTest.java
> +    protected Map<String, Object> addCaseTypeJurdisticaton() {
proected?

2022-05-16 16:29 UTC, nickwest1 commented on src/contractTest/java/uk/gov/hmcts/reform/et/syaapi/consumer/ccd/SubmitForCitizenConsumerTest.java
> +    public static DslPart buildCaseDetailsDsl(Long caseId) {
Dupe?

2022-05-16 16:29 UTC, nickwest1 commented on src/contractTest/java/uk/gov/hmcts/reform/et/syaapi/consumer/idam/JwksConsumerTest.java
> +        System.out.println(response);
No System.out.println's :)

2022-05-17 15:14 UTC, jthmcts approved these changes

2022-05-17 15:22 UTC, merged