Ret 1455
hmcts/et-sya-api pull request #95
Opened 2022-05-20 13:23 UTC by robin-ieong

https://tools.hmcts.net/jira/browse/RET-1455

### Change description ###
Add API integration and functional tests including a functional health check test.

 

Tasks:

Integration tests required to mock calls to external services like CCD APIs
Functional tests - make sure that API end point is working end to end with a functional test (no mocking)
Functional tests required for email notifications via Gov.UK Notify service
Create functional health check endpoint that can be called from Jenkins pipelines.
 

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x ] No
```

2022-05-23 10:34 UTC, jthmcts commented on src/integrationTest/java/uk/gov/hmcts/reform/et/syaapi/controllers/ManageCaseControllerIntegrationTest.java
> +        mockMvc = webAppContextSetup(wac).build();
You've already autowired this

2022-05-23 10:35 UTC, nickwest1 requested changes

2022-05-23 10:35 UTC, nickwest1 commented on src/functionalTest/java/uk/gov/hmcts/reform/et/syaapi/CreateUser.java
> +public class CreateUser {
Can't we use @Data, @AllArgsConstructor and @Getter here?

2022-05-23 10:35 UTC, nickwest1 commented on src/functionalTest/java/uk/gov/hmcts/reform/et/syaapi/IdamTestApiRequests.java
> +            log.error("Failed to get access token from loginResponse");
Include the exception on logging:
log.error("Failed to get access token from loginResponse", e);

Beyond this, if this fails, then should you not be throwing an exception on up given you can't extract the access token?  Don't just ignore that.

2022-05-23 10:35 UTC, nickwest1 commented on src/functionalTest/java/uk/gov/hmcts/reform/et/syaapi/Role.java
> +public class Role {
Again, should be able to use @DaTa, @AllArgsConstructor and @getter here, surely?

2022-05-23 10:35 UTC, nickwest1 commented on src/integrationTest/java/uk/gov/hmcts/reform/et/syaapi/controllers/ResourceLoader.java
> +}
Prefer not a static class, then you can inject the ObjectMappaer already available as a bean

2022-05-25 10:14 UTC, nickwest1 approved these changes

2022-05-25 12:30 UTC, jthmcts approved these changes

2022-05-27 15:16 UTC, merged